In [2]:
import networkx as nx
import os
import sys
import urllib
from sklearn.cluster import KMeans

In [4]:
url = '/Users/justindo/COMP790/cat.graphml'
graph = nx.read_graphml(url)

In [5]:
len(graph)

65

In [6]:
len(graph.edges())

1139

In [7]:
graph.edges()

OutEdgeView([('n0', 'n1'), ('n0', 'n2'), ('n0', 'n3'), ('n0', 'n4'), ('n0', 'n5'), ('n0', 'n9'), ('n0', 'n10'), ('n0', 'n11'), ('n1', 'n0'), ('n1', 'n2'), ('n1', 'n3'), ('n1', 'n4'), ('n1', 'n5'), ('n1', 'n7'), ('n1', 'n9'), ('n1', 'n10'), ('n1', 'n11'), ('n1', 'n14'), ('n2', 'n0'), ('n2', 'n1'), ('n2', 'n3'), ('n2', 'n4'), ('n2', 'n5'), ('n2', 'n6'), ('n2', 'n7'), ('n2', 'n9'), ('n2', 'n10'), ('n2', 'n11'), ('n2', 'n12'), ('n2', 'n13'), ('n2', 'n14'), ('n2', 'n16'), ('n2', 'n17'), ('n2', 'n40'), ('n2', 'n41'), ('n2', 'n42'), ('n3', 'n0'), ('n3', 'n1'), ('n3', 'n2'), ('n3', 'n4'), ('n3', 'n5'), ('n3', 'n7'), ('n3', 'n9'), ('n3', 'n10'), ('n3', 'n11'), ('n3', 'n15'), ('n3', 'n16'), ('n3', 'n17'), ('n3', 'n58'), ('n3', 'n59'), ('n4', 'n0'), ('n4', 'n1'), ('n4', 'n2'), ('n4', 'n3'), ('n4', 'n6'), ('n4', 'n8'), ('n4', 'n9'), ('n4', 'n11'), ('n4', 'n14'), ('n4', 'n15'), ('n4', 'n16'), ('n4', 'n17'), ('n4', 'n50'), ('n4', 'n51'), ('n4', 'n58'), ('n4', 'n59'), ('n5', 'n0'), ('n5', 'n1'), ('n5

In [8]:
graph['n0'] ## adjacency dict-like view keyed by neighbor to edge attributes

AtlasView({'n1': {}, 'n2': {}, 'n3': {}, 'n4': {}, 'n5': {}, 'n9': {}, 'n10': {}, 'n11': {}})

In [10]:
graph['n0']['n1'] ## all of the edges between n0 and n30

{}

In [11]:
graph['n0']['n1'][0] ## a single edge

KeyError: 0

In [12]:
graph.degree() ## degree of each node

DiDegreeView({'n0': 17, 'n1': 22, 'n2': 39, 'n3': 30, 'n4': 38, 'n5': 36, 'n6': 25, 'n7': 17, 'n8': 14, 'n9': 25, 'n10': 24, 'n11': 54, 'n12': 44, 'n13': 6, 'n14': 60, 'n15': 67, 'n16': 21, 'n17': 31, 'n18': 19, 'n19': 27, 'n20': 14, 'n21': 19, 'n22': 24, 'n23': 15, 'n24': 6, 'n25': 46, 'n26': 53, 'n27': 17, 'n28': 22, 'n29': 28, 'n30': 22, 'n31': 24, 'n32': 36, 'n33': 40, 'n34': 39, 'n35': 39, 'n36': 42, 'n37': 55, 'n38': 16, 'n39': 36, 'n40': 51, 'n41': 42, 'n42': 42, 'n43': 41, 'n44': 41, 'n45': 40, 'n46': 36, 'n47': 50, 'n48': 41, 'n49': 42, 'n50': 66, 'n51': 63, 'n52': 72, 'n53': 47, 'n54': 54, 'n55': 31, 'n56': 33, 'n57': 27, 'n58': 70, 'n59': 65, 'n60': 21, 'n61': 20, 'n62': 34, 'n63': 6, 'n64': 34})

In [25]:
# networkx clusteirng not supported for the multigraph type (a multigraph has multiple connections between the same pairs of nodes) 
# --> transform the multigraph into weighted digraph 

In [21]:
new_graph = nx.Graph()
for u, v in graph.edges():
    if new_graph.has_edge(u, v):
        new_graph[u][v]['weight'] += 1
    else:
        new_graph.add_edge(u, v, weight=1)

In [22]:
new_graph.edges()

EdgeView([('n0', 'n1'), ('n0', 'n2'), ('n0', 'n3'), ('n0', 'n4'), ('n0', 'n5'), ('n0', 'n9'), ('n0', 'n10'), ('n0', 'n11'), ('n0', 'n7'), ('n1', 'n2'), ('n1', 'n3'), ('n1', 'n4'), ('n1', 'n5'), ('n1', 'n7'), ('n1', 'n9'), ('n1', 'n10'), ('n1', 'n11'), ('n1', 'n14'), ('n1', 'n6'), ('n1', 'n42'), ('n2', 'n3'), ('n2', 'n4'), ('n2', 'n5'), ('n2', 'n6'), ('n2', 'n7'), ('n2', 'n9'), ('n2', 'n10'), ('n2', 'n11'), ('n2', 'n12'), ('n2', 'n13'), ('n2', 'n14'), ('n2', 'n16'), ('n2', 'n17'), ('n2', 'n40'), ('n2', 'n41'), ('n2', 'n42'), ('n2', 'n8'), ('n2', 'n25'), ('n2', 'n26'), ('n2', 'n36'), ('n3', 'n4'), ('n3', 'n5'), ('n3', 'n7'), ('n3', 'n9'), ('n3', 'n10'), ('n3', 'n11'), ('n3', 'n15'), ('n3', 'n16'), ('n3', 'n17'), ('n3', 'n58'), ('n3', 'n59'), ('n3', 'n36'), ('n3', 'n42'), ('n3', 'n50'), ('n3', 'n51'), ('n3', 'n52'), ('n4', 'n6'), ('n4', 'n8'), ('n4', 'n9'), ('n4', 'n11'), ('n4', 'n14'), ('n4', 'n15'), ('n4', 'n16'), ('n4', 'n17'), ('n4', 'n50'), ('n4', 'n51'), ('n4', 'n58'), ('n4', 'n59')

In [23]:
len(new_graph) # same amount of nodes

65

In [24]:
len(new_graph.edges()) # less edges

730

In [25]:
new_graph['n0'] # now we have weights instead of 32 separate edges

AtlasView({'n1': {'weight': 2}, 'n2': {'weight': 2}, 'n3': {'weight': 2}, 'n4': {'weight': 2}, 'n5': {'weight': 2}, 'n9': {'weight': 2}, 'n10': {'weight': 2}, 'n11': {'weight': 2}, 'n7': {'weight': 1}})

In [26]:
# https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.cluster.clustering.html
clusters = nx.clustering(new_graph, weight='weight')
clusters

{'n0': 0.8061701168277631,
 'n1': 0.6763701433402599,
 'n2': 0.42075564346396443,
 'n3': 0.46993938100984367,
 'n4': 0.446592829479302,
 'n5': 0.35560660524175675,
 'n9': 0.5363352276672775,
 'n10': 0.4659009470738263,
 'n11': 0.37083506401851973,
 'n7': 0.511964226027338,
 'n14': 0.3992374097932061,
 'n6': 0.4220573207838311,
 'n12': 0.4324077972169914,
 'n13': 0.9312335086613666,
 'n16': 0.4361002587815062,
 'n17': 0.4919252923238013,
 'n40': 0.4721130455718265,
 'n41': 0.6155998967496449,
 'n42': 0.43582132373723975,
 'n15': 0.3888027085101735,
 'n58': 0.31001939102503323,
 'n59': 0.30128842135774947,
 'n8': 0.49922298198068304,
 'n50': 0.37229616291905687,
 'n51': 0.3476792478665072,
 'n26': 0.3949203255245008,
 'n21': 0.541833588198857,
 'n22': 0.48542434911160837,
 'n36': 0.3644222882699906,
 'n38': 0.44283692947023234,
 'n47': 0.49739371442035607,
 'n48': 0.533744433592559,
 'n52': 0.37443838094496606,
 'n53': 0.5018055568161717,
 'n55': 0.6453953519312059,
 'n60': 0.62400475124

In [27]:
adj_matrix = nx.to_numpy_matrix(new_graph) # convert to adj matrix
adj_matrix

matrix([[0., 2., 2., ..., 0., 0., 0.],
        [2., 0., 2., ..., 0., 0., 0.],
        [2., 2., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 2., 0.],
        [0., 0., 0., ..., 2., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [45]:
kmeans = KMeans(n_clusters=12)
kmeans.fit(adj_matrix)

KMeans()

In [46]:
kmeans.labels_

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 3, 2, 3, 3, 3, 5, 5, 5, 4, 0, 0,
       3, 4, 4, 7, 7, 7, 5, 3, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 5, 5, 5,
       5, 2, 2, 7, 7, 1, 1, 1, 1, 5, 1, 7, 7, 7, 7, 1, 1, 2, 4, 2, 3],
      dtype=int32)

In [53]:
kmeans.cluster_centers_

array([[ 0.00000000e+00,  5.86510264e-04,  5.38826979e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -3.25260652e-19,  9.25921053e+01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [47]:
from sklearn.cluster import SpectralClustering
sc = SpectralClustering(12, affinity='precomputed', n_init=10, assign_labels='discretize')
results = sc.fit(adj_matrix)

In [48]:
results.labels_

array([5, 5, 5, 5, 3, 5, 5, 3, 6, 3, 5, 3, 6, 5, 5, 6, 2, 2, 2, 3, 0, 4,
       3, 3, 3, 1, 6, 1, 2, 4, 6, 6, 2, 6, 6, 0, 0, 0, 0, 2, 2, 2, 2, 2,
       2, 6, 6, 1, 1, 4, 4, 4, 2, 2, 4, 1, 1, 1, 1, 4, 4, 0, 2, 0, 0])

In [49]:
from sklearn.metrics import normalized_mutual_info_score

normalized_mutual_info_score(kmeans.labels_, results.labels_)

0.6148230115427012