In [46]:
import networkx as nx
import os
import sys
import urllib
from sklearn.cluster import KMeans

In [2]:
url = 'https://s3.amazonaws.com/connectome-graphs/fly/drosophila_medulla_1.graphml'
file = urllib.request.urlopen(url)
graph = nx.read_graphml(file)

In [6]:
len(graph)

1781

In [7]:
len(graph.edges())

33641

In [13]:
graph.edges()

OutMultiEdgeDataView([('n0', 'n1471'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n1472'), ('n0', 'n151'), ('n0', 'n151'), ('n0', 'n151'), ('n0', 'n312'), ('n0', 'n83'), ('n0', 'n83'), ('n0', 'n83'), ('n0', 'n30'), ('n0', 'n30'), ('n0', 'n30'), ('n0', 'n30'), ('n1', 'n9'), ('n1', 'n9'), ('n1', 'n9'), ('n1', 'n316'), ('n1', 'n316'), ('n1', 'n316'), ('n1', 'n316'), ('n1', 'n316'), ('n1', 'n114'), ('n1', 'n114'), ('n1', 'n114'), ('n1', 'n7'), ('n1', 'n7'), ('n1', 'n7'), ('n1', 'n7'), ('n1', 'n7'), ('n1', '

In [14]:
graph['n0'] ## adjacency dict-like view keyed by neighbor to edge attributes

AdjacencyView({'n1471': {0: {'pre.x': 5697.0, 'post.x': 5726.0, 'pre.y': 7408.0, 'post.y': 7373.0, 'pre.z': 168.0, 'post.z': 166.0, 'proofreading.details': '2 reached same anchor body'}}, 'n1472': {0: {'pre.x': 5697.0, 'post.x': 5734.0, 'pre.y': 7408.0, 'post.y': 7417.0, 'pre.z': 168.0, 'post.z': 167.0, 'proofreading.details': 'Both are orphan'}, 1: {'pre.x': 5697.0, 'post.x': 5703.0, 'pre.y': 7408.0, 'post.y': 7449.0, 'pre.z': 168.0, 'post.z': 167.0, 'proofreading.details': 'Both are orphan'}, 2: {'pre.x': 5697.0, 'post.x': 5738.0, 'pre.y': 7408.0, 'post.y': 7456.0, 'pre.z': 168.0, 'post.z': 168.0, 'proofreading.details': 'Both are orphan'}, 3: {'pre.x': 5637.0, 'post.x': 5593.0, 'pre.y': 7492.0, 'post.y': 7514.0, 'pre.z': 169.0, 'post.z': 169.0, 'proofreading.details': 'Both are orphan'}, 4: {'pre.x': 5637.0, 'post.x': 5671.0, 'pre.y': 7492.0, 'post.y': 7531.0, 'pre.z': 169.0, 'post.z': 169.0, 'proofreading.details': 'Both are orphan'}, 5: {'pre.x': 5562.0, 'post.x': 5583.0, 'pre.y':

In [15]:
graph['n0']['n30'] ## all of the edges between n0 and n30

AtlasView({0: {'pre.x': 5772.0, 'post.x': 5756.0, 'pre.y': 7512.0, 'post.y': 7547.0, 'pre.z': 176.0, 'post.z': 176.0, 'proofreading.details': '2 reached same named body'}, 1: {'pre.x': 5930.0, 'post.x': 5876.0, 'pre.y': 7353.0, 'post.y': 7361.0, 'pre.z': 188.0, 'post.z': 188.0, 'proofreading.details': 'Densely Named'}, 2: {'pre.x': 6096.0, 'post.x': 6068.0, 'pre.y': 7610.0, 'post.y': 7643.0, 'pre.z': 191.0, 'post.z': 191.0, 'proofreading.details': 'Densely Named'}, 3: {'pre.x': 6013.0, 'post.x': 5960.0, 'pre.y': 7525.0, 'post.y': 7539.0, 'pre.z': 196.0, 'post.z': 196.0, 'proofreading.details': 'Densely Named'}})

In [17]:
graph['n0']['n30'][0] ## a single edge

{'pre.x': 5772.0,
 'post.x': 5756.0,
 'pre.y': 7512.0,
 'post.y': 7547.0,
 'pre.z': 176.0,
 'post.z': 176.0,
 'proofreading.details': '2 reached same named body'}

In [22]:
graph.degree() ## degree of each node

DiMultiDegreeView({'n0': 44, 'n1': 128, 'n2': 52, 'n3': 230, 'n4': 1, 'n5': 1, 'n6': 17, 'n7': 183, 'n8': 6, 'n9': 229, 'n10': 12, 'n11': 27, 'n12': 46, 'n13': 13, 'n14': 3, 'n15': 15, 'n16': 4, 'n17': 11, 'n18': 7, 'n19': 20, 'n20': 549, 'n21': 102, 'n22': 9, 'n23': 52, 'n24': 12, 'n25': 6, 'n26': 8, 'n27': 80, 'n28': 30, 'n29': 8, 'n30': 115, 'n31': 7, 'n32': 7, 'n33': 18, 'n34': 194, 'n35': 1, 'n36': 3, 'n37': 99, 'n38': 116, 'n39': 1, 'n40': 22, 'n41': 8, 'n42': 1, 'n43': 17, 'n44': 28, 'n45': 6, 'n46': 306, 'n47': 570, 'n48': 841, 'n49': 244, 'n50': 1173, 'n51': 2, 'n52': 7, 'n53': 148, 'n54': 395, 'n55': 137, 'n56': 10, 'n57': 2, 'n58': 32, 'n59': 20, 'n60': 57, 'n61': 404, 'n62': 41, 'n63': 268, 'n64': 396, 'n65': 1, 'n66': 1, 'n67': 265, 'n68': 2, 'n69': 129, 'n70': 1, 'n71': 8, 'n72': 56, 'n73': 570, 'n74': 235, 'n75': 6, 'n76': 13, 'n77': 10, 'n78': 9, 'n79': 36, 'n80': 5, 'n81': 120, 'n82': 93, 'n83': 164, 'n84': 2, 'n85': 14, 'n86': 5, 'n87': 32, 'n88': 20, 'n89': 17, 'n90'

In [25]:
# networkx clusteirng not supported for the multigraph type (a multigraph has multiple connections between the same pairs of nodes) 
# --> transform the multigraph into weighted digraph 

In [30]:
new_graph = nx.DiGraph()
for u, v in graph.edges():
    if new_graph.has_edge(u, v):
        new_graph[u][v]['weight'] += 1
    else:
        new_graph.add_edge(u, v, weight=1)

In [31]:
new_graph.edges()

OutEdgeView([('n0', 'n1471'), ('n0', 'n1472'), ('n0', 'n151'), ('n0', 'n312'), ('n0', 'n83'), ('n0', 'n30'), ('n151', 'n1021'), ('n151', 'n167'), ('n151', 'n157'), ('n151', 'n1472'), ('n151', 'n129'), ('n151', 'n144'), ('n312', 'n1472'), ('n312', 'n287'), ('n312', 'n1531'), ('n312', 'n862'), ('n83', 'n387'), ('n83', 'n63'), ('n83', 'n87'), ('n83', 'n1472'), ('n83', 'n54'), ('n83', 'n955'), ('n83', 'n115'), ('n83', 'n211'), ('n83', 'n97'), ('n83', 'n88'), ('n83', 'n136'), ('n83', 'n1477'), ('n83', 'n124'), ('n83', 'n123'), ('n83', 'n30'), ('n83', 'n1481'), ('n83', 'n103'), ('n83', 'n279'), ('n83', 'n382'), ('n83', 'n61'), ('n83', 'n330'), ('n83', 'n380'), ('n83', 'n1561'), ('n83', 'n1565'), ('n83', 'n101'), ('n83', 'n388'), ('n83', 'n1483'), ('n83', 'n409'), ('n83', 'n375'), ('n83', 'n405'), ('n83', 'n185'), ('n83', 'n1573'), ('n83', 'n343'), ('n83', 'n83'), ('n83', 'n89'), ('n83', 'n82'), ('n83', 'n383'), ('n83', 'n1567'), ('n83', 'n341'), ('n30', 'n83'), ('n30', 'n61'), ('n30', 'n101'

In [32]:
len(new_graph) # same amount of nodes

1781

In [33]:
len(new_graph.edges()) # less edges

9735

In [34]:
new_graph['n0'] # now we have weights instead of 32 separate edges

AtlasView({'n1471': {'weight': 1}, 'n1472': {'weight': 32}, 'n151': {'weight': 3}, 'n312': {'weight': 1}, 'n83': {'weight': 3}, 'n30': {'weight': 4}})

In [36]:
# https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.cluster.clustering.html
clusters = nx.clustering(new_graph, weight='weight')
clusters

{'n0': 0.005775471012033627,
 'n1471': 0,
 'n1472': 0.0002739063371005973,
 'n151': 0.002207233652089726,
 'n312': 0.0014988501293493395,
 'n83': 0.0009429216144276652,
 'n30': 0.003695094365345229,
 'n1': 0.0013492937197145019,
 'n9': 0.0003054096995005917,
 'n316': 0.0017586443899292473,
 'n114': 0.0016883443597317026,
 'n7': 0.0013537572469300575,
 'n21': 0.003887137125411516,
 'n1506': 0.011203566919099508,
 'n130': 0.0009235032819015398,
 'n432': 0.0010116338965094518,
 'n402': 0.0008933546753264432,
 'n441': 0.0018987070810509421,
 'n623': 0.0018300230012490426,
 'n438': 0.0019209346201508118,
 'n431': 0.0006993291735449028,
 'n407': 0.0015192176828591143,
 'n454': 0.0007823616353402821,
 'n404': 0.0011160151600528051,
 'n428': 0.001753648633015606,
 'n444': 0.0020270092775570877,
 'n279': 0.0012298517607082001,
 'n449': 0.0025980914845479455,
 'n2': 0.00491140626777251,
 'n23': 0.000930536189236171,
 'n105': 0.0021891535989279507,
 'n116': 0.0011739155383523126,
 'n34': 0.004492

In [38]:
adj_matrix = nx.to_numpy_matrix(new_graph) # convert to adj matrix
adj_matrix

matrix([[ 0.,  1., 32., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  8., ...,  0.,  0.,  0.]])

In [ ]:
kmeans = KMeans(n_clusters=10)
kmeans.fit(adj_matrix)

In [52]:
kmeans.labels_

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [53]:
kmeans.cluster_centers_

array([[ 0.00000000e+00,  5.86510264e-04,  5.38826979e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -3.25260652e-19,  9.25921053e+01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])